import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ar" | "fr" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (l: Language) => void;
  isRTL: boolean;
  t: (key: string, vars?: Record<string, string>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.about": "About this project",
    "nav.creator": "The creator",
    // Home
    "home.title": "Search any medical condition.",
    "home.subtitle": "Medical search engine that helps you find reliable information about symptoms, conditions, and treatments in seconds",
    "home.placeholder": "Add symptoms... e.g. pain in the back, neck pain, headache...",
    "home.selected": "Selected symptoms",
    "narrow.searchBtn": "Search",
    "home.clearAll": "Clear all",
    "home.searchBtn": "Search for conditions",
    "home.popular": "Popular searches:",
    "home.trusted": "Reliable information from trusted medical sources",
    "home.disclaimer": "For informational purposes only. Always consult a healthcare professional.",
    "home.pop.headache": "Headache",
    "home.pop.chest": "Chest pain",
    "home.pop.fever": "Fever and cough",
    "home.pop.stomach": "Stomach ache",
    "home.pop.back": "Back pain",
    "home.pop.dizzy": "Dizziness",
    // Narrowing
    "narrow.searching": "Searching...",
    "narrow.results": "results",
    "narrow.query": "Query",
    "narrow.refine": "Refine Results",
    "narrow.relevant": "Most relevant",
    "narrow.common": "Common first",
    "narrow.urgent": "Urgent first",
    "narrow.ranking": "Ranking relevant conditions...",
    "narrow.related": "Related searches:",
    "narrow.matched": "Matched because:",
    "narrow.high": "High relevance",
    "narrow.moderate": "Moderate relevance",
    "narrow.related_cond": "Related condition",
    "narrow.clear": "Clear filters",
    // Result
    "result.matchScore": "Match score",
    "result.matchDesc": "Reflects how closely your query matched this condition in the index",
    "result.matched": "Matched symptoms",
    "result.disclaimer_title": "Not a medical diagnosis",
    "result.disclaimer_body": "This is informational guidance based on provided symptoms. Always consult a qualified healthcare professional for proper diagnosis and treatment.",
    "result.bm25": "BM25 score:",
    "result.risk": "Risk level",
    "result.urgent": "Urgent attention needed",
    "result.urgentDesc": "Call {n} if red-flag signs appear",
    "result.emergencyDesc": "See the clinical guidance section below for full warning signs",
    "result.orAE": "or go to A&E if:",
    "result.importantTreatment": "Important treatment information",
    "when.seeDoctor":    "When to see a doctor",
    "when.seekCare":     "When to seek care",
    "when.seeYourDoctor":"When to see your doctor",
    "when.callDoctor":   "When to call a doctor",
    "when.emergency":    "When to get emergency help",
    "when.seeDentist":   "When to see a dentist",
    "detail.symptoms":         "Symptoms",
    "detail.commonSymptoms":   "Common symptoms",
    "detail.generalSymptoms":  "General symptoms",
    "detail.earlySymptoms":    "Early symptoms",
    "detail.laterSymptoms":    "Later symptoms",
    "detail.mildSymptoms":     "Mild symptoms",
    "detail.emergencySymptoms":"Emergency symptoms",
    "detail.childrenSymptoms": "Symptoms in children",
    "detail.otherSymptoms":    "Other symptoms",
    "detail.causes":           "Causes",
    "detail.medicalCauses":    "Medical causes",
    "detail.physicalCauses":   "Physical causes",
    "detail.psychoCauses":     "Psychological causes",
    "detail.lifestyleCauses":  "Health & lifestyle causes",
    "detail.otherCauses":      "Other causes",
    "detail.complications":    "Complications",
    "detail.longTermComp":     "Long-term complications",
    "detail.eyeComp":          "Eye complications",
    "detail.physicalComp":     "Physical complications",
    "detail.pregnancyComp":    "Pregnancy complications",
    "detail.treatmentSideEff": "Side effects of treatment",
    "detail.otherComp":        "Other complications",
    "detail.lifestyleChoices": "Lifestyle choices",
    "treat.medicines":    "Medicines",
    "treat.surgery":      "Surgery",
    "treat.chemo":        "Chemotherapy",
    "treat.radio":        "Radiotherapy",
    "treat.targeted":     "Targeted Medicines & Immunotherapy",
    "treat.hormone":      "Hormone Therapy",
    "treat.biological":   "Biological & DMARD Treatments",
    "treat.talking":      "Talking Therapies",
    "treat.physio":       "Physiotherapy & Occupational Therapy",
    "treat.painRelief":   "Pain Relief",
    "treat.complementary":"Complementary Therapies",
    "treat.other":        "Other Treatments",
    "result.consult": "Consultation recommended",
    "result.consultDesc": "See a healthcare professional",
    "result.routine": "Routine monitoring",
    "result.routineDesc": "Usually manageable at home",
    "result.overview": "Overview",
    "result.whatToDo": "What to do",
    "result.risk_section": "Risk",
    
    "result.clinical": "Clinical",
    "result.details": "Details",
    "result.actions": "Actions",
    "result.refine": "Refine symptoms",
    "result.coverage": "Data coverage",
    "result.symptoms": "Symptoms",
    "result.causes": "Causes",
    "result.riskFactors": "Risk factors",
    "result.complications": "Complications",
    "result.treatment": "Treatment",
    "result.prevention": "Prevention",
    "result.clinicalGuidance": "Clinical guidance",
    "result.emergency": "Emergency — Call {n}",
    "result.seeDoctor": "See a doctor if:",
    "result.pharmacist": "See a pharmacist if:",
    "result.monitor": "Monitor",
    "result.monitorDesc": "Monitor symptoms over the next few hours, note any changes, and seek medical help if they worsen",
    "result.avoid": "Avoid",
    "result.avoidDesc": "Don't ignore severe or sudden new symptoms",
    "result.selfCare": "Self-care steps",
    "result.dontDo": "What to avoid",
    "result.whileWaiting": "While waiting for a doctor",
    "result.fullSymptoms": "Full symptoms",
    "result.trustedSources": "Trusted sources",
    "result.understanding": "Understanding the risk",
    "result.possibleComp": "Possible complications",
    "result.additionalDetails": "Additional details",
    "result.notDiagnosis": "Based on provided symptoms only — not a medical diagnosis",
    "result.translating": "Translating content...",
    "result.translateBtn": "Translate to {lang}",
    // Mobile CTA
    "cta.newSearch": "New Search",
    "cta.save": "Save Summary",
    "cta.doctor": "Talk to Doctor",
  },

  ar: {
    "nav.about": "عن المشروع",
    "nav.creator": "المطور",
    "home.title": "ابحث عن أي حالة طبية.",
    "home.subtitle": "محرك بحث طبي يساعدك في العثور على معلومات موثوقة حول الأعراض والحالات والعلاجات في ثوانٍ",
    "home.placeholder": "أضف الأعراض... مثال: ألم في الظهر، ألم الرقبة، صداع...",
    "home.selected": "الأعراض المختارة",
    "home.clearAll": "مسح الكل",
    "narrow.searchBtn": "بحث",
    "home.searchBtn": "ابحث عن الحالات",
    "home.popular": "عمليات البحث الشائعة:",
    "home.trusted": "معلومات موثوقة من مصادر طبية معتمدة",
    "home.disclaimer": "للأغراض التعليمية فقط. استشر دائماً أخصائي رعاية صحية.",
    "home.pop.headache": "صداع",
    "home.pop.chest": "ألم في الصدر",
    "home.pop.fever": "حمى وسعال",
    "home.pop.stomach": "ألم في المعدة",
    "home.pop.back": "ألم في الظهر",
    "home.pop.dizzy": "دوخة",
    "narrow.searching": "جاري البحث...",
    "narrow.results": "نتائج",
    "narrow.query": "استعلام",
    "narrow.refine": "تحسين النتائج",
    "narrow.relevant": "الأكثر صلة",
    "narrow.common": "شائع",
    "narrow.urgent": "عاجل",
    "narrow.ranking": "تصنيف الحالات ذات الصلة...",
    "narrow.related": "عمليات بحث ذات صلة:",
    "narrow.matched": "تم العثور عليها لأن:",
    "narrow.high": "صلة عالية",
    "narrow.moderate": "صلة متوسطة",
    "narrow.related_cond": "حالة ذات صلة",
    "narrow.clear": "مسح الفلاتر",
    "result.matchScore": "درجة التطابق",
    "result.matchDesc": "يعكس مدى تطابق استعلامك مع هذه الحالة في قاعدة البيانات",
    "result.matched": "الأعراض المطابقة",
    "result.disclaimer_title": "ليس تشخيصاً طبياً",
    "result.disclaimer_body": "هذه المعلومات إرشادية بناءً على الأعراض المقدمة. استشر دائماً مختصاً صحياً مؤهلاً للتشخيص والعلاج المناسبين.",
    "result.bm25": "نقاط BM25:",
    "result.risk": "مستوى الخطر",
    "result.urgent": "يستلزم اهتماماً عاجلاً",
    "result.urgentDesc": "اتصل بـ {n} إذا ظهرت علامات الخطر",
    "result.emergencyDesc": "راجع قسم التوجيه السريري أدناه للعلامات الكاملة",
    "result.orAE": "أو اذهب لأقرب طوارئ إذا:",
    "result.importantTreatment": "معلومات مهمة حول العلاج",
    "when.seeDoctor":    "متى ترى طبيباً",
    "when.seekCare":     "متى تطلب الرعاية",
    "when.seeYourDoctor":"متى ترى طبيبك",
    "when.callDoctor":   "متى تتصل بالطبيب",
    "when.emergency":    "متى تطلب مساعدة طارئة",
    "when.seeDentist":   "متى ترى طبيب الأسنان",
    "detail.symptoms":         "الأعراض",
    "detail.commonSymptoms":   "الأعراض الشائعة",
    "detail.generalSymptoms":  "الأعراض العامة",
    "detail.earlySymptoms":    "الأعراض المبكرة",
    "detail.laterSymptoms":    "الأعراض المتأخرة",
    "detail.mildSymptoms":     "الأعراض الخفيفة",
    "detail.emergencySymptoms":"أعراض الطوارئ",
    "detail.childrenSymptoms": "أعراض عند الأطفال",
    "detail.otherSymptoms":    "أعراض أخرى",
    "detail.causes":           "الأسباب",
    "detail.medicalCauses":    "الأسباب الطبية",
    "detail.physicalCauses":   "الأسباب الجسدية",
    "detail.psychoCauses":     "الأسباب النفسية",
    "detail.lifestyleCauses":  "أسباب نمط الحياة",
    "detail.otherCauses":      "أسباب أخرى",
    "detail.complications":    "المضاعفات",
    "detail.longTermComp":     "المضاعفات طويلة الأمد",
    "detail.eyeComp":          "مضاعفات العين",
    "detail.physicalComp":     "المضاعفات الجسدية",
    "detail.pregnancyComp":    "مضاعفات الحمل",
    "detail.treatmentSideEff": "آثار جانبية للعلاج",
    "detail.otherComp":        "مضاعفات أخرى",
    "detail.lifestyleChoices": "خيارات نمط الحياة",
    "treat.medicines":    "الأدوية",
    "treat.surgery":      "الجراحة",
    "treat.chemo":        "العلاج الكيميائي",
    "treat.radio":        "العلاج الإشعاعي",
    "treat.targeted":     "الأدوية المستهدفة والمناعية",
    "treat.hormone":      "العلاج الهرموني",
    "treat.biological":   "العلاجات البيولوجية",
    "treat.talking":      "العلاج النفسي",
    "treat.physio":       "العلاج الطبيعي والوظيفي",
    "treat.painRelief":   "تخفيف الألم",
    "treat.complementary":"العلاجات التكميلية",
    "treat.other":        "علاجات أخرى",
    "result.consult": "استشارة موصى بها",
    "result.consultDesc": "راجع مختص رعاية صحية",
    "result.routine": "مراقبة روتينية",
    "result.routineDesc": "يمكن إدارتها في المنزل عادةً",
    "result.overview": "نظرة عامة",
    "result.whatToDo": "ما يجب فعله",
    "result.risk_section": "الخطر",
    "result.clinical": "التوجيه السريري",
    "result.details": "التفاصيل",
    "result.actions": "الإجراءات",
    "result.refine": "حسّن الأعراض",
    "result.coverage": "تغطية البيانات",
    "result.symptoms": "الأعراض",
    "result.causes": "الأسباب",
    "result.riskFactors": "عوامل الخطر",
    "result.complications": "المضاعفات",
    "result.treatment": "العلاج",
    "result.prevention": "الوقاية",
    "result.clinicalGuidance": "التوجيه السريري",
    "result.emergency": "طوارئ — اتصل بـ {n}",
    "result.seeDoctor": "راجع الطبيب إذا:",
    "result.pharmacist": "راجع الصيدلاني إذا:",
    "result.monitor": "راقب",
    "result.monitorDesc": "راقب الأعراض للساعات القادمة وسجّل أي تغيير، واطلب مساعدة طبية إذا ساءت الحالة",
    "result.avoid": "تجنب",
    "result.avoidDesc": "لا تتجاهل الأعراض الحادة أو المفاجئة",
    "result.selfCare": "الرعاية الذاتية",
    "result.dontDo": "ما يجب تجنبه",
    "result.whileWaiting": "أثناء انتظار الطبيب",
    "result.fullSymptoms": "الأعراض الكاملة",
    "result.trustedSources": "مصادر موثوقة",
    "result.understanding": "فهم مستوى الخطر",
    "result.possibleComp": "المضاعفات المحتملة",
    "result.additionalDetails": "تفاصيل إضافية",
    "result.notDiagnosis": "بناءً على الأعراض المقدمة فقط — ليس تشخيصاً طبياً",
    "result.translating": "جاري الترجمة...",
    "result.translateBtn": "ترجم إلى {lang}",
    "cta.newSearch": "بحث جديد",
    "cta.save": "حفظ الملخص",
    "cta.doctor": "تحدث إلى طبيب",
  },

  fr: {
    "nav.about": "À propos du projet",
    "nav.creator": "Le créateur",
    "home.title": "Recherchez n'importe quelle condition médicale.",
    "home.subtitle": "Moteur de recherche médical qui vous aide à trouver des informations fiables sur les symptômes, conditions et traitements en quelques secondes",
    "home.placeholder": "Ajouter des symptômes... ex. douleur au dos, douleur au cou, mal de tête...",
    "home.selected": "Symptômes sélectionnés",
    "home.clearAll": "Tout effacer",
    "home.searchBtn": "Rechercher des conditions",
    "home.popular": "Recherches populaires :",
    "narrow.searchBtn": "Rechercher",
    "home.trusted": "Informations fiables de sources médicales reconnues",
    "home.disclaimer": "À titre informatif uniquement. Consultez toujours un professionnel de santé.",
    "home.pop.headache": "Maux de tête",
    "home.pop.chest": "Douleur thoracique",
    "home.pop.fever": "Fièvre et toux",
    "home.pop.stomach": "Mal d'estomac",
    "home.pop.back": "Mal de dos",
    "home.pop.dizzy": "Vertiges",
    "narrow.searching": "Recherche en cours...",
    "narrow.results": "résultats",
    "narrow.query": "Requête",
    "narrow.refine": "Affiner les résultats",
    "narrow.relevant": "Plus pertinent",
    "narrow.common": "Plus fréquent",
    "narrow.urgent": "Urgent d'abord",
    "narrow.ranking": "Classement des conditions pertinentes...",
    "narrow.related": "Recherches connexes :",
    "narrow.matched": "Correspondance car :",
    "narrow.high": "Haute pertinence",
    "narrow.moderate": "Pertinence modérée",
    "narrow.related_cond": "Condition connexe",
    "narrow.clear": "Effacer les filtres",
    "result.matchScore": "Score de correspondance",
    "result.matchDesc": "Reflète la proximité de votre requête avec cette condition dans l'index",
    "result.matched": "Symptômes correspondants",
    "result.disclaimer_title": "Pas un diagnostic médical",
    "result.disclaimer_body": "Ces informations sont indicatives basées sur les symptômes fournis. Consultez toujours un professionnel de santé qualifié.",
    "result.bm25": "Score BM25 :",
    "result.risk": "Niveau de risque",
    "result.urgent": "Attention urgente requise",
    "result.urgentDesc": "Appelez le {n} si des signes d'alerte apparaissent",
    "result.emergencyDesc": "Consultez la section orientation clinique ci-dessous pour les signes d'alarme complets",
    "result.orAE": "ou allez aux urgences si :",
    "result.importantTreatment": "Informations importantes sur le traitement",
    "when.seeDoctor":    "Quand consulter un médecin",
    "when.seekCare":     "Quand chercher des soins",
    "when.seeYourDoctor":"Quand voir votre médecin",
    "when.callDoctor":   "Quand appeler un médecin",
    "when.emergency":    "Quand obtenir une aide d'urgence",
    "when.seeDentist":   "Quand voir un dentiste",
    "detail.symptoms":         "Symptômes",
    "detail.commonSymptoms":   "Symptômes courants",
    "detail.generalSymptoms":  "Symptômes généraux",
    "detail.earlySymptoms":    "Symptômes précoces",
    "detail.laterSymptoms":    "Symptômes tardifs",
    "detail.mildSymptoms":     "Symptômes légers",
    "detail.emergencySymptoms":"Symptômes d'urgence",
    "detail.childrenSymptoms": "Symptômes chez les enfants",
    "detail.otherSymptoms":    "Autres symptômes",
    "detail.causes":           "Causes",
    "detail.medicalCauses":    "Causes médicales",
    "detail.physicalCauses":   "Causes physiques",
    "detail.psychoCauses":     "Causes psychologiques",
    "detail.lifestyleCauses":  "Causes liées au mode de vie",
    "detail.otherCauses":      "Autres causes",
    "detail.complications":    "Complications",
    "detail.longTermComp":     "Complications à long terme",
    "detail.eyeComp":          "Complications oculaires",
    "detail.physicalComp":     "Complications physiques",
    "detail.pregnancyComp":    "Complications de grossesse",
    "detail.treatmentSideEff": "Effets secondaires du traitement",
    "detail.otherComp":        "Autres complications",
    "detail.lifestyleChoices": "Choix de mode de vie",
    "treat.medicines":    "Médicaments",
    "treat.surgery":      "Chirurgie",
    "treat.chemo":        "Chimiothérapie",
    "treat.radio":        "Radiothérapie",
    "treat.targeted":     "Médicaments ciblés et immunothérapie",
    "treat.hormone":      "Hormonothérapie",
    "treat.biological":   "Traitements biologiques",
    "treat.talking":      "Thérapies par la parole",
    "treat.physio":       "Physiothérapie et ergothérapie",
    "treat.painRelief":   "Soulagement de la douleur",
    "treat.complementary":"Thérapies complémentaires",
    "treat.other":        "Autres traitements",
    "result.consult": "Consultation recommandée",
    "result.consultDesc": "Consultez un professionnel de santé",
    "result.routine": "Surveillance de routine",
    "result.routineDesc": "Généralement gérable à domicile",
    "result.overview": "Aperçu",
    "result.whatToDo": "Que faire",
    "result.risk_section": "Risque",
    "result.clinical": "Clinique",
    "result.details": "Détails",
    "result.actions": "Actions",
    "result.refine": "Affiner les symptômes",
    "result.coverage": "Couverture des données",
    "result.symptoms": "Symptômes",
    "result.causes": "Causes",
    "result.riskFactors": "Facteurs de risque",
    "result.complications": "Complications",
    "result.treatment": "Traitement",
    "result.prevention": "Prévention",
    "result.clinicalGuidance": "Conseils cliniques",
    "result.emergency": "Urgence — Appelez le {n}",
    "result.seeDoctor": "Consultez un médecin si :",
    "result.pharmacist": "Consultez un pharmacien si :",
    "result.monitor": "Surveiller",
    "result.monitorDesc": "Surveillez les symptômes pendant les prochaines heures et consultez si ça empire",
    "result.avoid": "Éviter",
    "result.avoidDesc": "Ne pas ignorer les symptômes graves ou soudains",
    "result.selfCare": "Soins personnels",
    "result.dontDo": "Ce qu'il faut éviter",
    "result.whileWaiting": "En attendant le médecin",
    "result.fullSymptoms": "Symptômes complets",
    "result.trustedSources": "Sources fiables",
    "result.understanding": "Comprendre le niveau de risque",
    "result.possibleComp": "Complications possibles",
    "result.additionalDetails": "Détails supplémentaires",
    "result.notDiagnosis": "Basé sur les symptômes fournis uniquement — pas un diagnostic médical",
    "result.translating": "Traduction en cours...",
    "result.translateBtn": "Traduire en {lang}",
    "cta.newSearch": "Nouvelle recherche",
    "cta.save": "Enregistrer le résumé",
    "cta.doctor": "Parler à un médecin",
  },

  es: {
    "nav.about": "Sobre el proyecto",
    "nav.creator": "El creador",
    "home.title": "Busca cualquier condición médica.",
    "home.subtitle": "Motor de búsqueda médica que te ayuda a encontrar información confiable sobre síntomas, condiciones y tratamientos en segundos",
    "home.placeholder": "Añadir síntomas... p. ej., dolor de espalda, dolor de cuello, dolor de cabeza...",
    "home.selected": "Síntomas seleccionados",
    "home.clearAll": "Borrar todo",
    "home.searchBtn": "Buscar condiciones",
    "home.popular": "Búsquedas populares:",
    "home.trusted": "Información confiable de fuentes médicas reconocidas",
    "home.disclaimer": "Solo con fines informativos. Siempre consulta a un profesional de salud.",
    "home.pop.headache": "Dolor de cabeza",
    "home.pop.chest": "Dolor en el pecho",
    "narrow.searchBtn": "Buscar",
    "home.pop.fever": "Fiebre y tos",
    "home.pop.stomach": "Dolor de estómago",
    "home.pop.back": "Dolor de espalda",
    "home.pop.dizzy": "Mareos",
    "narrow.searching": "Buscando...",
    "narrow.results": "resultados",
    "narrow.query": "Consulta",
    "narrow.refine": "Refinar resultados",
    "narrow.relevant": "Más relevante",
    "narrow.common": "Más común",
    "narrow.urgent": "Urgente primero",
    "narrow.ranking": "Clasificando condiciones relevantes...",
    "narrow.related": "Búsquedas relacionadas:",
    "narrow.matched": "Coincidió porque:",
    "narrow.high": "Alta relevancia",
    "narrow.moderate": "Relevancia moderada",
    "narrow.related_cond": "Condición relacionada",
    "narrow.clear": "Borrar filtros",
    "result.matchScore": "Puntuación de coincidencia",
    "result.matchDesc": "Refleja qué tan cerca está tu consulta de esta condición en el índice",
    "result.matched": "Síntomas coincidentes",
    "result.disclaimer_title": "No es un diagnóstico médico",
    "result.disclaimer_body": "Esta es información orientativa basada en los síntomas proporcionados. Siempre consulta a un profesional de salud calificado.",
    "result.bm25": "Puntuación BM25:",
    "result.risk": "Nivel de riesgo",
    "result.urgent": "Atención urgente requerida",
    "result.urgentDesc": "Llama al {n} si aparecen señales de alerta",
    "result.emergencyDesc": "Consulta la sección de orientación clínica a continuación para ver las señales de alerta completas",
    "result.orAE": "o ve a urgencias si:",
    "result.importantTreatment": "Información importante sobre el tratamiento",
    "when.seeDoctor":    "Cuándo ver a un médico",
    "when.seekCare":     "Cuándo buscar atención",
    "when.seeYourDoctor":"Cuándo ver a tu médico",
    "when.callDoctor":   "Cuándo llamar a un médico",
    "when.emergency":    "Cuándo obtener ayuda de emergencia",
    "when.seeDentist":   "Cuándo ver a un dentista",
    "detail.symptoms":         "Síntomas",
    "detail.commonSymptoms":   "Síntomas comunes",
    "detail.generalSymptoms":  "Síntomas generales",
    "detail.earlySymptoms":    "Síntomas tempranos",
    "detail.laterSymptoms":    "Síntomas tardíos",
    "detail.mildSymptoms":     "Síntomas leves",
    "detail.emergencySymptoms":"Síntomas de emergencia",
    "detail.childrenSymptoms": "Síntomas en niños",
    "detail.otherSymptoms":    "Otros síntomas",
    "detail.causes":           "Causas",
    "detail.medicalCauses":    "Causas médicas",
    "detail.physicalCauses":   "Causas físicas",
    "detail.psychoCauses":     "Causas psicológicas",
    "detail.lifestyleCauses":  "Causas de estilo de vida",
    "detail.otherCauses":      "Otras causas",
    "detail.complications":    "Complicaciones",
    "detail.longTermComp":     "Complicaciones a largo plazo",
    "detail.eyeComp":          "Complicaciones oculares",
    "detail.physicalComp":     "Complicaciones físicas",
    "detail.pregnancyComp":    "Complicaciones del embarazo",
    "detail.treatmentSideEff": "Efectos secundarios del tratamiento",
    "detail.otherComp":        "Otras complicaciones",
    "detail.lifestyleChoices": "Opciones de estilo de vida",
    "treat.medicines":    "Medicamentos",
    "treat.surgery":      "Cirugía",
    "treat.chemo":        "Quimioterapia",
    "treat.radio":        "Radioterapia",
    "treat.targeted":     "Medicamentos dirigidos e inmunoterapia",
    "treat.hormone":      "Terapia hormonal",
    "treat.biological":   "Tratamientos biológicos",
    "treat.talking":      "Terapias de conversación",
    "treat.physio":       "Fisioterapia y terapia ocupacional",
    "treat.painRelief":   "Alivio del dolor",
    "treat.complementary":"Terapias complementarias",
    "treat.other":        "Otros tratamientos",
    "result.consult": "Consulta recomendada",
    "result.consultDesc": "Consulta a un profesional de salud",
    "result.routine": "Monitoreo rutinario",
    "result.routineDesc": "Generalmente manejable en casa",
    "result.overview": "Descripción general",
    "result.whatToDo": "Qué hacer",
    "result.risk_section": "Riesgo",
    "result.clinical": "Clínico",
    "result.details": "Detalles",
    "result.actions": "Acciones",
    "result.refine": "Refinar síntomas",
    "result.coverage": "Cobertura de datos",
    "result.symptoms": "Síntomas",
    "result.causes": "Causas",
    "result.riskFactors": "Factores de riesgo",
    "result.complications": "Complicaciones",
    "result.treatment": "Tratamiento",
    "result.prevention": "Prevención",
    "result.clinicalGuidance": "Orientación clínica",
    "result.emergency": "Emergencia — Llama al {n}",
    "result.seeDoctor": "Consulta a un médico si:",
    "result.pharmacist": "Consulta a un farmacéutico si:",
    "result.monitor": "Monitorear",
    "result.monitorDesc": "Monitorea los síntomas durante las próximas horas y busca ayuda médica si empeoran",
    "result.avoid": "Evitar",
    "result.avoidDesc": "No ignores síntomas graves o nuevos repentinos",
    "result.selfCare": "Autocuidado",
    "result.dontDo": "Qué evitar",
    "result.whileWaiting": "Mientras esperas al médico",
    "result.fullSymptoms": "Síntomas completos",
    "result.trustedSources": "Fuentes confiables",
    "result.understanding": "Comprender el nivel de riesgo",
    "result.possibleComp": "Posibles complicaciones",
    "result.additionalDetails": "Detalles adicionales",
    "result.notDiagnosis": "Basado solo en síntomas proporcionados — no es un diagnóstico médico",
    "result.translating": "Traduciendo contenido...",
    "result.translateBtn": "Traducir a {lang}",
    "cta.newSearch": "Nueva búsqueda",
    "cta.save": "Guardar resumen",
    "cta.doctor": "Hablar con un médico",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string, vars?: Record<string, string>) => {
    let str = translations[language][key] ?? translations["en"][key] ?? key;
    if (vars) Object.entries(vars).forEach(([k, v]) => { str = str.replace(`{${k}}`, v); });
    return str;
  };

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      isRTL: language === "ar",
      t,
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}